## «*El mundo exige resultados. No cuentes a otros tus dolores del parto. Muéstrales al niño.*»

### [Indira Gandhi](https://es.wikipedia.org/wiki/Indira_Gandhi)

# ppi_SI_06_Pandas

Actividad individual.

Utilice el dataset seleccionado en **SI01 Repositorio csv de Kaggle**.

Diligencie las casillas indicadas siguiendo las normas de estilo del PEP8.

# Preparación del ejercicio

*   Importe las librerías requeridas
*   Lea el dataset a utilizar desde una url

Sugerencia: suba el dataset a Googledrive y luego publíquelo como página web. El siguiente enlace le indica cómo hacerlo: [Cómo publicar archivos de Documentos, Hojas de cálculo, Presentaciones y Formularios de Google](https://support.google.com/docs/answer/183965?hl=es-419&co=GENIE.Platform%3DDesktop).

Nota: si lo desea puede utilizar otro método para obtener la url del dataset.

In [ ]:
# Importar las librerías necesarias
import pandas as pd

# Conocer la versiones de las librerías instaladas
print(f"La versión instalada de Pandas es: {pd.__version__}\n")

# Guardar en la variable 'ruta' la url del dataset
ruta = ('https://docs.google.com/spreadsheets/d/e/'
        '2PACX-1vTFw_DicCY7BH56cQPE3rQEMjj88R8cqMADrC6rwJ'
        'UeWxVN6o2CDYfTsJtzd9768BA8KXNIC6MIEb-M/pub'
        '?gid=1816493422&single=true&output=csv')

# Cargar el dataset a partir de la ruta establecida
pokemon_dataset = constructores_df = pd.read_csv(ruta, sep=',')

# Verificar la lectura del dataset
pokemon_dataset

La versión instalada de Pandas es: 1.5.3

,Pokemon Id,Pokedex Number,Pokemon Name,Classification,Alternate Form Name,Original Pokemon ID,Legendary Type,Pokemon Height,Pokemon Weight,Primary Type,...,Speed EV,EV Yield Total,Catch Rate,Experience Growth,Experience Growth Total,Primary Egg Group,Secondary Egg Group,Egg Cycle Count,Pre-Evolution Pokemon Id,Evolution Details
0,1,1,"""Bulbasaur""","""Seed Pokémon""",NaN,NaN,NaN,0.7,6.9,"""Grass""",...,0,1,45,"""Medium Slow""",1059860,"""Monster""","""Grass""",20,NaN,NaN
1,2,2,"""Ivysaur""","""Seed Pokémon""",NaN,NaN,NaN,1.0,13.0,"""Grass""",...,0,2,45,"""Medium Slow""",1059860,"""Monster""","""Grass""",20,1.0,"""Level 16"""
2,3,3,"""Venusaur""","""Seed Pokémon""",NaN,NaN,NaN,2.0,100.0,"""Grass""",...,0,3,45,"""Medium Slow""",1059860,"""Monster""","""Grass""",20,2.0,"""Level 32"""
3,4,3,"""Venusaur""","""Seed Pokémon""","""Mega""",3.0,NaN,2.4,155.5,"""Grass""",...,0,3,45,"""Medium Slow""",1059860,"""Monster""","""Grass""",20,NaN,NaN
4,1526,3,"""Venusaur""","""Seed Pokémon""","""Gigantamax""",3.0,NaN,24.0,0.0,"""Grass""",...,0,3,45,"""Medium Slow""",1059860,"""Monster""","""Grass""",20,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1230,1685,1004,"""Chi-Yu""","""Ruinous Pokémon""",NaN,NaN,"""Sub-Legendary""",0.4,4.9,"""Dark""",...,0,3,6,"""Slow""",1250000,"""No Eggs Discovered""",NaN,50,NaN,NaN
1231,1742,1005,"""Roaring Moon""","""Paradox Pokémon""",NaN,NaN,NaN,2.0,380.0,"""Dragon""",...,0,3,10,"""Slow""",1250000,"""No Eggs Discovered""",NaN,50,NaN,NaN
1232,1749,1006,"""Iron Valiant""","""Paradox Pokémon""",NaN,NaN,NaN,1.4,35.0,"""Fairy""",...,0,3,10,"""Slow""",1250000,"""No Eggs Discovered""",NaN,50,NaN,NaN
1233,1647,1007,"""Koraidon""","""Paradox Pokémon""",NaN,NaN,"""Legendary""",2.5,303.0,"""Fighting""",...,0,3,3,"""Slow""",1250000,"""No Eggs Discovered""",NaN,0,NaN,NaN
1234,1648,1008,"""Miraidon""","""Paradox Pokémon""",NaN,NaN,"""Legendary""",3.5,240.0,"""Electric""",...,0,3,3,"""Slow""",1250000,"""No Eggs Discovered""",NaN,0,NaN,NaN

Warning: Total number of columns (45) exceeds max_columns (20) limiting to first (20) columns.

# Explorar el dataset

Muestre las principales características del dataset utilizando pandas.

En particular muestre los nombres de las columnas y sus tipos; el índice del dataset; la forma del dataset.

In [ ]:
# Se imprime la forma del DataFrame
print(f"La forma del DataFrame es: {pokemon_dataset.shape}\n")

# Se imprime el indice del DataFrame
print(f"El indíce del DataFrame es: {pokemon_dataset.index}\n")

# La representación como un arreglo de NumPy es:
print(f"La representación como un arreglo\
 de NumPy es:\n {pokemon_dataset.values}\n")

# Se imprimen los nombres de las columnas y sus tipos en el DataFrame
print(f"Los tipos de las columnas del DataFrame \
son:\n\n{pokemon_dataset.dtypes}")

# Transformar el dataset

## df_00

Cree el df_00 con las siguientes características:

Diez columnas (dentro de las diez columnas deben estar la primera y la última columna del dataset original).

Diez filas (las filas deben corresponder a las cinco primeras filas y las cinco últimas filas del dataset original).

Muestre el resultado y las características del DataFrame.

In [ ]:
import pandas as pd

# Se filtran las primeras 5 y últimas 5 filas
df_00 = pd.concat([pokemon_dataset.head(5), pokemon_dataset.tail(5)], axis=0)

# Se filtran 10 columnas incluyendo la primera y última
df_00 = df_00.iloc[:, [0, 2, 3, 9, 10, 23, 24, 25, 11, -1]]
print(df_00, "\n")

## df_01

Modifique el índice del df_00 creado en el paso anterior.

Opción 1: utilice una de las columnas de df_00 como el nuevo índice.

Opción 2: cree el índice a partir de una secuencia cronológica.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Se coloca la columna Pokemon Id como índice
df_01 = df_00.set_index('Pokemon Id')

# Se imprime el indice del DataFrame
print(f"El indíce del DataFrame es: {df_01.index}\n")

# Se imprime la forma del DataFrame
print(f"La forma del DataFrame es: {df_01.shape}\n")

# Se imprime el DataFrame
print(df_01, "\n")

## df_02

Cambie los nombres de las columnas de df_01 a "Primera", "segunda", etcétera.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Se genera una copia del df_01 para no modificarlo
df_02 = df_01.copy()

# Se cambia el nombre de las columnas
df_02.columns = ["Primera", "Segunda", "Tercera", "Cuarta",
                 "Quinta", "Sexta", "Séptima", "Octava", "Novena"]

# Se imprimen los nombres de las columnas
print(f"Los nombres de las columnas son: \n\
{df_02.columns.to_list()}")

# Se imprime el DataFrame
print(df_02, "\n")

## df_03

Utilizando el método **loc** seleccione los elementos que se encuentran entre la tercera y la sexta fila y en las columnas cuarta, quinta y octava de df_02.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Se filtra el DataFrame df_02 con loc
df_03 = df_02.loc[3:1685, ['Cuarta', 'Quinta', 'Octava']]

# Se imprime la forma del DataFrame
print(f"La forma del DataFrame es: {df_03.shape}\n")

# Se imprime el DataFrame
print(df_03, "\n")

## df_04

Utilizando el método **iloc** seleccione los elementos que se encuentran entre la tercera y la sexta fila y en las columnas cuarta, quinta y octava de df_02.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Se filtra el DataFrame df_02 con iloc
df_04 = df_02.iloc[2:6, [3, 4, 7]]

# Se imprime la forma del DataFrame
print(f"La forma del DataFrame es: {df_04.shape}\n")

# Se imprime el DataFrame
print(df_04, "\n")

## df_05

Calcule el promedio de una de las columnas numéricas de df_02.

Cree el DataFrame df_05 conservando todas las columnas de df_02 y seleccionando los valores superiores al promedio en la columna numérica que tomó como referencia para el ejercicio.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Se saca el promedio de la columna sexta
mean = df_02['Sexta'].mean()

# Se filtran los datos que superen el promedio
df_05 = df_02[df_02['Sexta'] > mean]

# Se imprime la forma del DataFrame
print(f"La forma del DataFrame es: {df_05.shape}\n")

# Se imprime el DataFrame
print(df_05, "\n")

## df_06

Seleccione una columna de df_02 que contenga una variable categórica (si no hay variables categóricas cree una columna con variables categóricas a partir de una columna numérica de df_02).

Utilice el método **groupby** para analizar la información de df_02 a partir de la variable categórica seleccionada.

Muestre el resultado y las características del DataFrame.

In [ ]:
# Se agrupa el df_02 con la cuarta columna
# La cuarta columna representa el tipo del Pokemon
df_06 = df_02.groupby('Cuarta')["Primera"].agg('count')

# Se imprimen los grupos generados
print(f"Los datos agrupados son:\n {df_06}\n")

# Se imprime la moda del DataFrame
moda = df_02.groupby('Cuarta')['Cuarta'].agg('count').idxmax()
print(f'El tipo Pokemón que más se repite es: {moda}')

## df_07

Cree una tabla dinámica, utilizando el método **pivottable**, para analizar la información de df_02

Muestre el resultado y las características del DataFrame.

In [ ]:
# Se genera la tabla dinámica con las operaciones:
# Suma, Conteo, Media y Máximo
df_07 = df_02.pivot_table(
    index=['Cuarta'],
    values=['Sexta', 'Séptima'],
    aggfunc=['sum', 'count', 'median', 'max']
    )

print(f'La tabla dinámica es:\n\n {df_07}')